version: 2
updates:
  # .NET dependencies
  - package-ecosystem: "nuget"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "DegrassiAaron"
    labels:
      - "dependencies"
      - "dotnet"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Frontend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "DegrassiAaron"
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for React (requires manual review)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "DegrassiAaron"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "DegrassiAaron"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
